/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnereinkRouteImport } from './routes/partnereink'
import { Route as PalyazatokRouteImport } from './routes/palyazatok'
import { Route as AdatkezelesiTajekoztatoRouteImport } from './routes/adatkezelesi-tajekoztato'
import { Route as IndexRouteImport } from './routes/index'

const PartnereinkRoute = PartnereinkRouteImport.update({
  id: '/partnereink',
  path: '/partnereink',
  getParentRoute: () => rootRouteImport,
} as any)
const PalyazatokRoute = PalyazatokRouteImport.update({
  id: '/palyazatok',
  path: '/palyazatok',
  getParentRoute: () => rootRouteImport,
} as any)
const AdatkezelesiTajekoztatoRoute = AdatkezelesiTajekoztatoRouteImport.update({
  id: '/adatkezelesi-tajekoztato',
  path: '/adatkezelesi-tajekoztato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adatkezelesi-tajekoztato': typeof AdatkezelesiTajekoztatoRoute
  '/palyazatok': typeof PalyazatokRoute
  '/partnereink': typeof PartnereinkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adatkezelesi-tajekoztato': typeof AdatkezelesiTajekoztatoRoute
  '/palyazatok': typeof PalyazatokRoute
  '/partnereink': typeof PartnereinkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adatkezelesi-tajekoztato': typeof AdatkezelesiTajekoztatoRoute
  '/palyazatok': typeof PalyazatokRoute
  '/partnereink': typeof PartnereinkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adatkezelesi-tajekoztato' | '/palyazatok' | '/partnereink'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adatkezelesi-tajekoztato' | '/palyazatok' | '/partnereink'
  id:
    | '__root__'
    | '/'
    | '/adatkezelesi-tajekoztato'
    | '/palyazatok'
    | '/partnereink'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdatkezelesiTajekoztatoRoute: typeof AdatkezelesiTajekoztatoRoute
  PalyazatokRoute: typeof PalyazatokRoute
  PartnereinkRoute: typeof PartnereinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partnereink': {
      id: '/partnereink'
      path: '/partnereink'
      fullPath: '/partnereink'
      preLoaderRoute: typeof PartnereinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palyazatok': {
      id: '/palyazatok'
      path: '/palyazatok'
      fullPath: '/palyazatok'
      preLoaderRoute: typeof PalyazatokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adatkezelesi-tajekoztato': {
      id: '/adatkezelesi-tajekoztato'
      path: '/adatkezelesi-tajekoztato'
      fullPath: '/adatkezelesi-tajekoztato'
      preLoaderRoute: typeof AdatkezelesiTajekoztatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdatkezelesiTajekoztatoRoute: AdatkezelesiTajekoztatoRoute,
  PalyazatokRoute: PalyazatokRoute,
  PartnereinkRoute: PartnereinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
